server:
  port: 6869 #服务端口

spring:
  application:
    name: demo-microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/770679957/cloud-demo-config.git
          search-paths: project-a
          username: X
          password: X
        label: master

